local FishingZonesEstuariesDefaults = require "FishingZonesEstuariesDefaults"
local FishingZonesGroundDefaults = require "FishingZonesGroundDefaults"
Events.OnInitGlobalModData.Add(FishingZonesEstuariesDefaults.init)
Events.OnInitGlobalModData.Add(FishingZonesGroundDefaults.init)