require 'Items/ProceduralDistributions'
                                                                
table.insert(ProceduralDistributions["list"]["ButcherFish"].items,"Base.AtlanticCod")
table.insert(ProceduralDistributions["list"]["ButcherFish"].items, 5)
table.insert(ProceduralDistributions["list"]["ButcherFish"].items,"Base.AtlanticHalibut")
table.insert(ProceduralDistributions["list"]["ButcherFish"].items, 5)
table.insert(ProceduralDistributions["list"]["ButcherFish"].items,"Base.AtlanticHerring")
table.insert(ProceduralDistributions["list"]["ButcherFish"].items, 5)

table.insert(ProceduralDistributions["list"]["ButcherFreezer"].items,"Base.AtlanticCod")
table.insert(ProceduralDistributions["list"]["ButcherFreezer"].items, 6)
table.insert(ProceduralDistributions["list"]["ButcherFreezer"].items,"Base.AtlanticHalibut")
table.insert(ProceduralDistributions["list"]["ButcherFreezer"].items, 1)
table.insert(ProceduralDistributions["list"]["ButcherFreezer"].items,"Base.AtlanticMackerel")
table.insert(ProceduralDistributions["list"]["ButcherFreezer"].items, 2)

table.insert(ProceduralDistributions["list"]["ChineseKitchenFreezer"].items,"Base.WhitePerch")
table.insert(ProceduralDistributions["list"]["ChineseKitchenFreezer"].items, 2)
table.insert(ProceduralDistributions["list"]["ChineseKitchenFreezer"].items,"Base.BrookTrout")
table.insert(ProceduralDistributions["list"]["ChineseKitchenFreezer"].items, 2)
table.insert(ProceduralDistributions["list"]["ChineseKitchenFreezer"].items,"Base.BrownTrout")
table.insert(ProceduralDistributions["list"]["ChineseKitchenFreezer"].items, 2)

table.insert(ProceduralDistributions["list"]["DeepFryKitchenFreezer"].items,"Base.BrownTrout")
table.insert(ProceduralDistributions["list"]["DeepFryKitchenFreezer"].items, 1)
table.insert(ProceduralDistributions["list"]["DeepFryKitchenFreezer"].items,"Base.AtlanticSalmon")
table.insert(ProceduralDistributions["list"]["DeepFryKitchenFreezer"].items, 1)
table.insert(ProceduralDistributions["list"]["DeepFryKitchenFreezer"].items,"Base.AtlanticHerring")
table.insert(ProceduralDistributions["list"]["DeepFryKitchenFreezer"].items, 1)

table.insert(ProceduralDistributions["list"]["FishChipsKitchenButcher"].items,"Base.AtlanticHalibut")
table.insert(ProceduralDistributions["list"]["FishChipsKitchenButcher"].items, 1)
table.insert(ProceduralDistributions["list"]["FishChipsKitchenButcher"].items,"Base.AtlanticHerring")
table.insert(ProceduralDistributions["list"]["FishChipsKitchenButcher"].items, 1)
table.insert(ProceduralDistributions["list"]["FishChipsKitchenButcher"].items,"Base.AtlanticSalmon")
table.insert(ProceduralDistributions["list"]["FishChipsKitchenButcher"].items, 1)

table.insert(ProceduralDistributions["list"]["FishChipsKitchenFreezer"].items,"Base.AtlanticSalmon")
table.insert(ProceduralDistributions["list"]["FishChipsKitchenFreezer"].items, 3)
table.insert(ProceduralDistributions["list"]["FishChipsKitchenFreezer"].items,"Base.Pollack")
table.insert(ProceduralDistributions["list"]["FishChipsKitchenFreezer"].items, 2)
table.insert(ProceduralDistributions["list"]["FishChipsKitchenFreezer"].items,"Base.Haddock")
table.insert(ProceduralDistributions["list"]["FishChipsKitchenFreezer"].items, 1)

table.insert(ProceduralDistributions["list"]["FreezerGeneric"].items,"Base.Pollack")
table.insert(ProceduralDistributions["list"]["FreezerGeneric"].items, 4)
table.insert(ProceduralDistributions["list"]["FreezerGeneric"].items,"Base.AtlanticSalmon")
table.insert(ProceduralDistributions["list"]["FreezerGeneric"].items, 3)
table.insert(ProceduralDistributions["list"]["FreezerGeneric"].items,"Base.Haddock")
table.insert(ProceduralDistributions["list"]["FreezerGeneric"].items, 2)

table.insert(ProceduralDistributions["list"]["FreezerRich"].items,"Base.AtlanticSalmon")
table.insert(ProceduralDistributions["list"]["FreezerRich"].items, 6)
table.insert(ProceduralDistributions["list"]["FreezerRich"].items,"Base.BrownTrout")
table.insert(ProceduralDistributions["list"]["FreezerRich"].items, 4)
table.insert(ProceduralDistributions["list"]["FreezerRich"].items,"Base.AtlanticHerring")
table.insert(ProceduralDistributions["list"]["FreezerRich"].items, 2)

table.insert(ProceduralDistributions["list"]["RestaurantKitchenFreezer"].items,"Base.AtlanticSalmon")
table.insert(ProceduralDistributions["list"]["RestaurantKitchenFreezer"].items, 1)

table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items,"Base.AtlanticSalmon")
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, 9)
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items,"Base.AtlanticHerring")
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, 9)
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items,"Base.AtlanticHalibut")
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, 9)
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items,"Base.AtlanticMackerel")
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, 9)
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items,"Base.SummerFlounder")
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, 9)

table.insert(ProceduralDistributions["list"]["SeafoodKitchenFreezer"].items,"Base.AtlanticCod")
table.insert(ProceduralDistributions["list"]["SeafoodKitchenFreezer"].items, 9)
table.insert(ProceduralDistributions["list"]["SeafoodKitchenFreezer"].items,"Base.Haddock")
table.insert(ProceduralDistributions["list"]["SeafoodKitchenFreezer"].items, 9)
table.insert(ProceduralDistributions["list"]["SeafoodKitchenFreezer"].items,"Base.Pollack")
table.insert(ProceduralDistributions["list"]["SeafoodKitchenFreezer"].items, 9)

table.insert(ProceduralDistributions["list"]["StoreKitchenButcher"].items,"Base.Pollack")
table.insert(ProceduralDistributions["list"]["StoreKitchenButcher"].items, 2)
table.insert(ProceduralDistributions["list"]["StoreKitchenButcher"].items,"Base.Haddock")
table.insert(ProceduralDistributions["list"]["StoreKitchenButcher"].items, 2)
table.insert(ProceduralDistributions["list"]["StoreKitchenButcher"].items,"Base.AtlanticSalmon")
table.insert(ProceduralDistributions["list"]["StoreKitchenButcher"].items, 2)

table.insert(ProceduralDistributions["list"]["SushiKitchenFreezer"].items,"Base.AtlanticSalmon")
table.insert(ProceduralDistributions["list"]["SushiKitchenFreezer"].items, 5)
