--- Atlantic Cod :
local AtlanticCod = {};
AtlanticCod.name = "Atlantic Cod";
AtlanticCod.item = "Base.AtlanticCod";
AtlanticCod.lure = {};
table.insert(AtlanticCod.lure, "Worm");
table.insert(AtlanticCod.lure, "Cricket");
table.insert(AtlanticCod.lure, "Grasshopper");
table.insert(AtlanticCod.lure, "Cockroach");
table.insert(AtlanticCod.lure, "FishingTackle");
table.insert(AtlanticCod.lure, "FishingTackle2");
AtlanticCod.little = {};
AtlanticCod.medium = {};
AtlanticCod.big = {};
AtlanticCod.little.minSize = 23;
AtlanticCod.little.maxSize = 40;
AtlanticCod.medium.minSize = 40;
AtlanticCod.medium.maxSize = 65;
AtlanticCod.big.minSize = 65;
AtlanticCod.big.maxSize = 75;
AtlanticCod.little.weightChange = 60;
AtlanticCod.medium.weightChange = 45;
AtlanticCod.big.weightChange = 30;
table.insert(fishes, AtlanticCod);
--- Atlantic Halibut :
local AtlanticHalibut = {};
AtlanticHalibut.name = "Atlantic Halibut";
AtlanticHalibut.item = "Base.AtlanticHalibut";
AtlanticHalibut.lure = {};
table.insert(AtlanticHalibut.lure, "Worm");
table.insert(AtlanticHalibut.lure, "Cricket");
table.insert(AtlanticHalibut.lure, "Grasshopper");
table.insert(AtlanticHalibut.lure, "Cockroach");
table.insert(AtlanticHalibut.lure, "FishingTackle");
table.insert(AtlanticHalibut.lure, "FishingTackle2");
AtlanticHalibut.little = {};
AtlanticHalibut.medium = {};
AtlanticHalibut.big = {};
AtlanticHalibut.little.minSize = 33;
AtlanticHalibut.little.maxSize = 48;
AtlanticHalibut.medium.minSize = 48;
AtlanticHalibut.medium.maxSize = 58;
AtlanticHalibut.big.minSize = 58;
AtlanticHalibut.big.maxSize = 100;
AtlanticHalibut.little.weightChange = 60;
AtlanticHalibut.medium.weightChange = 45;
AtlanticHalibut.big.weightChange = 16;
table.insert(fishes, AtlanticHalibut);
--- Atlantic Herring :
local AtlanticHerring = {};
AtlanticHerring.name = "Atlantic Herring";
AtlanticHerring.item = "Base.AtlanticHerring";
AtlanticHerring.lure = {};
table.insert(AtlanticHerring.lure, "Worm");
table.insert(AtlanticHerring.lure, "Cricket");
table.insert(AtlanticHerring.lure, "Grasshopper");
table.insert(AtlanticHerring.lure, "Cockroach");
table.insert(AtlanticHerring.lure, "FishingTackle");
table.insert(AtlanticHerring.lure, "FishingTackle2");
AtlanticHerring.little = {};
AtlanticHerring.medium = {};
AtlanticHerring.big = {};
AtlanticHerring.little.minSize = 10;
AtlanticHerring.little.maxSize = 19;
AtlanticHerring.medium.minSize = 19;
AtlanticHerring.medium.maxSize = 33;
AtlanticHerring.big.minSize = 33;
AtlanticHerring.big.maxSize = 40;
AtlanticHerring.little.weightChange = 30;
AtlanticHerring.medium.weightChange = 20;
AtlanticHerring.big.weightChange = 10;
table.insert(fishes, AtlanticHerring);
--- AtlanticMackerel :
local AtlanticMackerel = {};
AtlanticMackerel.name = "Atlantic Mackerel";
AtlanticMackerel.item = "Base.AtlanticMackerel";
AtlanticMackerel.lure = {};
table.insert(AtlanticMackerel.lure, "Worm");
table.insert(AtlanticMackerel.lure, "Cricket");
table.insert(AtlanticMackerel.lure, "Grasshopper");
table.insert(AtlanticMackerel.lure, "Cockroach");
table.insert(AtlanticMackerel.lure, "FishingTackle");
table.insert(AtlanticMackerel.lure, "FishingTackle2");
AtlanticMackerel.little = {};
AtlanticMackerel.medium = {};
AtlanticMackerel.big = {};
AtlanticMackerel.little.minSize = 11;
AtlanticMackerel.little.maxSize = 25;
AtlanticMackerel.medium.minSize = 25;
AtlanticMackerel.medium.maxSize = 35;
AtlanticMackerel.big.minSize = 35;
AtlanticMackerel.big.maxSize = 45;
AtlanticMackerel.little.weightChange = 30;
AtlanticMackerel.medium.weightChange = 20;
AtlanticMackerel.big.weightChange = 10;
table.insert(fishes, AtlanticMackerel);
--- AtlanticSalmon :
local AtlanticSalmon = {};
AtlanticSalmon.name = "Atlantic Salmon";
AtlanticSalmon.item = "Base.AtlanticSalmon";
AtlanticSalmon.lure = {};
table.insert(AtlanticSalmon.lure, "Worm");
table.insert(AtlanticSalmon.lure, "Cricket");
table.insert(AtlanticSalmon.lure, "Grasshopper");
table.insert(AtlanticSalmon.lure, "Cockroach");
table.insert(AtlanticSalmon.lure, "FishingTackle");
table.insert(AtlanticSalmon.lure, "FishingTackle2");
AtlanticSalmon.little = {};
AtlanticSalmon.medium = {};
AtlanticSalmon.big = {};
AtlanticSalmon.little.minSize = 25;
AtlanticSalmon.little.maxSize = 65;
AtlanticSalmon.medium.minSize = 65;
AtlanticSalmon.medium.maxSize = 75;
AtlanticSalmon.big.minSize = 75;
AtlanticSalmon.big.maxSize = 85;
AtlanticSalmon.little.weightChange = 50;
AtlanticSalmon.medium.weightChange = 40;
AtlanticSalmon.big.weightChange = 30;
table.insert(fishes, AtlanticSalmon);
--- AtlanticTomcod :
local AtlanticTomcod = {};
AtlanticTomcod.name = "Atlantic Tomcod";
AtlanticTomcod.item = "Base.AtlanticTomcod";
AtlanticTomcod.lure = {};
table.insert(AtlanticTomcod.lure, "Worm");
table.insert(AtlanticTomcod.lure, "Baitfish");
table.insert(AtlanticTomcod.lure, "Cricket");
table.insert(AtlanticTomcod.lure, "Grasshopper");
table.insert(AtlanticTomcod.lure, "Cockroach");
table.insert(AtlanticTomcod.lure, "FishingTackle");
table.insert(AtlanticTomcod.lure, "FishingTackle2");
AtlanticTomcod.little = {};
AtlanticTomcod.medium = {};
AtlanticTomcod.big = {};
AtlanticTomcod.little.minSize = 10;
AtlanticTomcod.little.maxSize = 15;
AtlanticTomcod.medium.minSize = 15;
AtlanticTomcod.medium.maxSize = 20;
AtlanticTomcod.big.minSize = 20;
AtlanticTomcod.big.maxSize = 30;
AtlanticTomcod.little.weightChange = 30;
AtlanticTomcod.medium.weightChange = 20;
AtlanticTomcod.big.weightChange = 10;
table.insert(fishes, AtlanticTomcod);
--- SummerFlounder :
local SummerFlounder = {};
SummerFlounder.name = "Summer Flounder";
SummerFlounder.item = "Base.SummerFlounder";
SummerFlounder.lure = {};
table.insert(SummerFlounder.lure, "Worm");
table.insert(SummerFlounder.lure, "Cricket");
table.insert(SummerFlounder.lure, "Grasshopper");
table.insert(SummerFlounder.lure, "Cockroach");
table.insert(SummerFlounder.lure, "FishingTackle");
table.insert(SummerFlounder.lure, "FishingTackle2");
SummerFlounder.little = {};
SummerFlounder.medium = {};
SummerFlounder.big = {};
SummerFlounder.little.minSize = 20;
SummerFlounder.little.maxSize = 40;
SummerFlounder.medium.minSize = 40;
SummerFlounder.medium.maxSize = 50;
SummerFlounder.big.minSize = 50;
SummerFlounder.big.maxSize = 65;
SummerFlounder.little.weightChange = 30;
SummerFlounder.medium.weightChange = 20;
SummerFlounder.big.weightChange = 10;
table.insert(fishes, SummerFlounder);
--- Haddock :
local Haddock = {};
Haddock.name = "Haddock";
Haddock.item = "Base.Haddock";
Haddock.lure = {};
table.insert(Haddock.lure, "Worm");
table.insert(Haddock.lure, "Cricket");
table.insert(Haddock.lure, "Grasshopper");
table.insert(Haddock.lure, "Cockroach");
table.insert(Haddock.lure, "FishingTackle");
table.insert(Haddock.lure, "FishingTackle2");
Haddock.little = {};
Haddock.medium = {};
Haddock.big = {};
Haddock.little.minSize = 11;
Haddock.little.maxSize = 25;
Haddock.medium.minSize = 25;
Haddock.medium.maxSize = 45;
Haddock.big.minSize = 45;
Haddock.big.maxSize = 80;
Haddock.little.weightChange = 50;
Haddock.medium.weightChange = 40;
Haddock.big.weightChange = 30;
table.insert(fishes, Haddock);
--- Lumpfish :
local Lumpfish = {};
Lumpfish.name = "Lumpfish";
Lumpfish.item = "Base.Lumpfish";
Lumpfish.lure = {};
table.insert(Lumpfish.lure, "Worm");
table.insert(Lumpfish.lure, "Cricket");
table.insert(Lumpfish.lure, "Grasshopper");
table.insert(Lumpfish.lure, "Cockroach");
table.insert(Lumpfish.lure, "FishingTackle");
table.insert(Lumpfish.lure, "FishingTackle2");
Lumpfish.little = {};
Lumpfish.medium = {};
Lumpfish.big = {};
Lumpfish.little.minSize = 15;
Lumpfish.little.maxSize = 30;
Lumpfish.medium.minSize = 30;
Lumpfish.medium.maxSize = 45;
Lumpfish.big.minSize = 45;
Lumpfish.big.maxSize = 50;
Lumpfish.little.weightChange = 30;
Lumpfish.medium.weightChange = 20;
Lumpfish.big.weightChange = 10;
table.insert(fishes, Lumpfish);
--- Pollack :
local Pollack = {};
Pollack.name = "Pollack";
Pollack.item = "Base.Pollack";
Pollack.lure = {};
table.insert(Pollack.lure, "Worm");
table.insert(Pollack.lure, "Cricket");
table.insert(Pollack.lure, "Grasshopper");
table.insert(Pollack.lure, "Cockroach");
table.insert(Pollack.lure, "FishingTackle");
table.insert(Pollack.lure, "FishingTackle2");
Pollack.little = {};
Pollack.medium = {};
Pollack.big = {};
Pollack.little.minSize = 25;
Pollack.little.maxSize = 35;
Pollack.medium.minSize = 35;
Pollack.medium.maxSize = 75;
Pollack.big.minSize = 75;
Pollack.big.maxSize = 90;
Pollack.little.weightChange = 40;
Pollack.medium.weightChange = 30;
Pollack.big.weightChange = 20;
table.insert(fishes, Pollack);
--- RainbowSmelt :
local RainbowSmelt = {};
RainbowSmelt.name = "Rainbow Smelt";
RainbowSmelt.item = "Base.RainbowSmelt";
RainbowSmelt.lure = {};
table.insert(RainbowSmelt.lure, "Worm");
table.insert(RainbowSmelt.lure, "Cricket");
table.insert(RainbowSmelt.lure, "Grasshopper");
table.insert(RainbowSmelt.lure, "Cockroach");
table.insert(RainbowSmelt.lure, "FishingTackle");
table.insert(RainbowSmelt.lure, "FishingTackle2");
RainbowSmelt.little = {};
RainbowSmelt.medium = {};
RainbowSmelt.big = {};
RainbowSmelt.little.minSize = 10;
RainbowSmelt.little.maxSize = 18;
RainbowSmelt.medium.minSize = 18;
RainbowSmelt.medium.maxSize = 23;
RainbowSmelt.big.minSize = 23;
RainbowSmelt.big.maxSize = 30;
RainbowSmelt.little.weightChange = 30;
RainbowSmelt.medium.weightChange = 20;
RainbowSmelt.big.weightChange = 10;
table.insert(fishes, RainbowSmelt);
--- SpinyDogfish :
local SpinyDogfish = {};
SpinyDogfish.name = "Spiny Dogfish";
SpinyDogfish.item = "Base.SpinyDogfish";
SpinyDogfish.lure = {};
table.insert(SpinyDogfish.lure, "Worm");
table.insert(SpinyDogfish.lure, "Cricket");
table.insert(SpinyDogfish.lure, "Grasshopper");
table.insert(SpinyDogfish.lure, "Cockroach");
table.insert(SpinyDogfish.lure, "FishingTackle");
table.insert(SpinyDogfish.lure, "FishingTackle2");
SpinyDogfish.little = {};
SpinyDogfish.medium = {};
SpinyDogfish.big = {};
SpinyDogfish.little.minSize = 30;
SpinyDogfish.little.maxSize = 45;
SpinyDogfish.medium.minSize = 45;
SpinyDogfish.medium.maxSize = 65;
SpinyDogfish.big.minSize = 65;
SpinyDogfish.big.maxSize = 100;
SpinyDogfish.little.weightChange = 50;
SpinyDogfish.medium.weightChange = 40;
SpinyDogfish.big.weightChange = 30;
table.insert(fishes, SpinyDogfish);
--- StripedBass :
local StripedBass = {};
StripedBass.name = "Striped Bass";
StripedBass.item = "Base.StripedBass";
StripedBass.lure = {};
table.insert(StripedBass.lure, "Worm");
table.insert(StripedBass.lure, "Cricket");
table.insert(StripedBass.lure, "Grasshopper");
table.insert(StripedBass.lure, "Cockroach");
table.insert(StripedBass.lure, "FishingTackle");
table.insert(StripedBass.lure, "FishingTackle2");
StripedBass.little = {};
StripedBass.medium = {};
StripedBass.big = {};
StripedBass.little.minSize = 20;
StripedBass.little.maxSize = 35;
StripedBass.medium.minSize = 35;
StripedBass.medium.maxSize = 65;
StripedBass.big.minSize = 65;
StripedBass.big.maxSize = 120;
StripedBass.little.weightChange = 50;
StripedBass.medium.weightChange = 40;
StripedBass.big.weightChange = 30;
table.insert(fishes, StripedBass);
--- WhitePerch :
local WhitePerch = {};
WhitePerch.name = "White Perch";
WhitePerch.item = "Base.WhitePerch";
WhitePerch.lure = {};
table.insert(WhitePerch.lure, "Worm");
table.insert(WhitePerch.lure, "Cricket");
table.insert(WhitePerch.lure, "Grasshopper");
table.insert(WhitePerch.lure, "Cockroach");
table.insert(WhitePerch.lure, "FishingTackle");
table.insert(WhitePerch.lure, "FishingTackle2");
WhitePerch.little = {};
WhitePerch.medium = {};
WhitePerch.big = {};
WhitePerch.little.minSize = 16;
WhitePerch.little.maxSize = 30;
WhitePerch.medium.minSize = 30;
WhitePerch.medium.maxSize = 40;
WhitePerch.big.minSize = 40;
WhitePerch.big.maxSize = 50;
WhitePerch.little.weightChange = 30;
WhitePerch.medium.weightChange = 20;
WhitePerch.big.weightChange = 10;
table.insert(fishes, WhitePerch);
--- WinterFlounder :
local WinterFlounder = {};
WinterFlounder.name = "Winter Flounder";
WinterFlounder.item = "Base.WinterFlounder";
WinterFlounder.lure = {};
table.insert(WinterFlounder.lure, "Worm");
table.insert(WinterFlounder.lure, "Cricket");
table.insert(WinterFlounder.lure, "Grasshopper");
table.insert(WinterFlounder.lure, "Cockroach");
table.insert(WinterFlounder.lure, "FishingTackle");
table.insert(WinterFlounder.lure, "FishingTackle2");
WinterFlounder.little = {};
WinterFlounder.medium = {};
WinterFlounder.big = {};
WinterFlounder.little.minSize = 25;
WinterFlounder.little.maxSize = 50;
WinterFlounder.medium.minSize = 50;
WinterFlounder.medium.maxSize = 65;
WinterFlounder.big.minSize = 65;
WinterFlounder.big.maxSize = 75;
WinterFlounder.little.weightChange = 40;
WinterFlounder.medium.weightChange = 30;
WinterFlounder.big.weightChange = 20;
table.insert(fishes, WinterFlounder);
--- BrookTrout :
local BrookTrout = {};
BrookTrout.name = "Brook Trout";
BrookTrout.item = "Base.BrookTrout";
BrookTrout.lure = {};
table.insert(BrookTrout.lure, "Worm");
table.insert(BrookTrout.lure, "Cricket");
table.insert(BrookTrout.lure, "Grasshopper");
table.insert(BrookTrout.lure, "Cockroach");
table.insert(BrookTrout.lure, "FishingTackle");
table.insert(BrookTrout.lure, "FishingTackle2");
BrookTrout.little = {};
BrookTrout.medium = {};
BrookTrout.big = {};
BrookTrout.little.minSize = 12;
BrookTrout.little.maxSize = 35;
BrookTrout.medium.minSize = 35;
BrookTrout.medium.maxSize = 65;
BrookTrout.big.minSize = 65;
BrookTrout.big.maxSize = 75;
BrookTrout.little.weightChange = 50;
BrookTrout.medium.weightChange = 40;
BrookTrout.big.weightChange = 30;
table.insert(fishes, BrookTrout);
--- BrownTrout :
local BrownTrout = {};
BrownTrout.name = "Brown Trout";
BrownTrout.item = "Base.BrownTrout";
BrownTrout.lure = {};
table.insert(BrownTrout.lure, "Worm");
table.insert(BrownTrout.lure, "Cricket");
table.insert(BrownTrout.lure, "Grasshopper");
table.insert(BrownTrout.lure, "Cockroach");
table.insert(BrownTrout.lure, "FishingTackle");
table.insert(BrownTrout.lure, "FishingTackle2");
BrownTrout.little = {};
BrownTrout.medium = {};
BrownTrout.big = {};
BrownTrout.little.minSize = 25;
BrownTrout.little.maxSize = 35;
BrownTrout.medium.minSize = 35;
BrownTrout.medium.maxSize = 55;
BrownTrout.big.minSize = 55;
BrownTrout.big.maxSize = 65;
BrownTrout.little.weightChange = 40;
BrownTrout.medium.weightChange = 30;
BrownTrout.big.weightChange = 20;
table.insert(fishes, BrownTrout);
--- Gaspereau :
local Gaspereau = {};
Gaspereau.name = "Gaspereau";
Gaspereau.item = "Base.Gaspereau";
Gaspereau.lure = {};
table.insert(Gaspereau.lure, "Worm");
table.insert(Gaspereau.lure, "Cricket");
table.insert(Gaspereau.lure, "Grasshopper");
table.insert(Gaspereau.lure, "Cockroach");
table.insert(Gaspereau.lure, "FishingTackle");
table.insert(Gaspereau.lure, "FishingTackle2");
Gaspereau.little = {};
Gaspereau.medium = {};
Gaspereau.big = {};
Gaspereau.little.minSize = 10;
Gaspereau.little.maxSize = 20;
Gaspereau.medium.minSize = 20;
Gaspereau.medium.maxSize = 25;
Gaspereau.big.minSize = 25;
Gaspereau.big.maxSize = 30;
Gaspereau.little.weightChange = 30;
Gaspereau.medium.weightChange = 20;
Gaspereau.big.weightChange = 10;
table.insert(fishes, Gaspereau);
--- Brown Bullhead Catfish :
local BrownBullheadCatfish = {};
BrownBullheadCatfish.name = "Brown Bullhead Catfish";
BrownBullheadCatfish.item = "Base.BrownBullheadCatfish";
BrownBullheadCatfish.lure = {};
table.insert(BrownBullheadCatfish.lure, "Worm");
table.insert(BrownBullheadCatfish.lure, "BaitFish");
BrownBullheadCatfish.little = {};
BrownBullheadCatfish.medium = {};
BrownBullheadCatfish.big = {};
BrownBullheadCatfish.little.minSize = 25;
BrownBullheadCatfish.little.maxSize = 45;
BrownBullheadCatfish.medium.minSize = 45;
BrownBullheadCatfish.medium.maxSize = 55;
BrownBullheadCatfish.big.minSize = 55;
BrownBullheadCatfish.big.maxSize = 65;
BrownBullheadCatfish.little.weightChange = 30;
BrownBullheadCatfish.medium.weightChange = 20;
BrownBullheadCatfish.big.weightChange = 10;
table.insert(fishes, BrownBullheadCatfish);